✨😮Updating all SIG pages for Fall 2024
acm-uic/acm-uic.github.io pull request #1029
Opened 2024-09-18 01:51 UTC by clee231

## Description 

We have a ton of new SIGs! Let's get them on the website!

## Issues

## Checklist

- [ ] I've labeled the PR appropriately.
- [ ] I've have built the website and verified that my changes work.
- [ ] I've linked the appropriate issues and related PRs.

2024-09-18 03:15 UTC, lowpolyneko requested changes
looks good to me otherwise :3

2024-09-18 03:15 UTC, lowpolyneko commented on SIGs/Active/siggame.mdx
> -- Zachary Robbins: zlr2 (at) uic.edu
Ethan's email is eky2@uic.edu if you wanna keep the contact info up-to-date.

2024-09-18 03:15 UTC, lowpolyneko commented on SIGs/Active/sigsysadmin.mdx
>  - Soham Gumaste
you should add meeeee ;)

2024-09-18 13:16 UTC, clee231 commented on SIGs/Active/sigsysadmin.mdx
>  - Soham Gumaste
Are you okay with your real name here? Or would you prefer another alias like your Github username or netid?

2024-09-18 19:32 UTC, lowpolyneko commented on SIGs/Active/sigsysadmin.mdx
>  - Soham Gumaste
real name is fine haha, idrc with this account

2024-09-19 06:23 UTC, bmiddha approved these changes

2024-09-19 07:29 UTC, lowpolyneko approved these changes

2024-09-19 07:30 UTC, lowpolyneko commented
i forget that i have write access to this repo sometimes... i applied my suggestions myself :D

2024-09-19 07:30 UTC, merged