Add secretaries
acm-uic/acm-uic.github.io pull request #156
Opened 2021-11-08 15:37 UTC by Masacaai

## Description 

Add secretaries for 2021-2022 to officers.md
## Issues

## Checklist

- [x] I've labeled the PR appropriately.
- [ ] I've have built the website and verified that my changes work.
- [ ] I've linked the appropriate issues and related PRs.

2021-11-08 17:02 UTC, clee231 requested changes

2021-11-08 17:02 UTC, clee231 commented on src/pages/officers.md
> +| Secretary                         | Aaqel Shaik<br />Himaniben Patel<br />Sam Effendy<br />Aqsa Arif<br />Ishi Agarwal | mshai4@...<br />hpate248@...<br />seffe2@...<br />aarif20@...<br />iagarw5@
Let's be consistent.
```suggestion
| Secretary                         | Aaqel Shaik<br />Himaniben Patel<br />Sam Effendy<br />Aqsa Arif<br />Ishi Agarwal | mshai4@...<br />hpate248@...<br />seffe2@...<br />aarif20@...<br />iagarw5@... |
```

2021-11-08 17:52 UTC, Masacaai reviewed
Sorry, forgot abt the ellipses at the end.

2021-11-08 19:49 UTC, clee231 approved these changes

2021-11-09 01:51 UTC, bmiddha approved these changes

2021-11-09 01:51 UTC, merged