Add documentation for the door setup
acm-uic/acm-uic.github.io pull request #513
Opened 2022-11-17 03:32 UTC by SohamG

## Description 

Add documentation of the newly refurbished door controller setup. 

## Issues

Discord bot is jank. Need to polish and upload source code.

## Checklist

- [X] I've labeled the PR appropriately.
- [X] I've have built the website and verified that my changes work.
- [X] I've linked the appropriate issues and related PRs.

2022-11-17 05:09 UTC, bmiddha commented on docs/kb/office-door.md
> +## Wishlist
nit: wish list is 2 words.
the wish list should also be moved to an issue in the code repo.

2022-11-17 05:09 UTC, bmiddha commented on docs/kb/office-door.md
> +### Deployment Information
The issue with keeping the deployment and implementation specific docs here is that they can *easily* get out of sync. It's better to keep this stuff in the repo and point to it from here instead.

We should document the existence of the project, what it's about, how it works with other projects, where to look at the code (implementation, deployment docs, etc.)

2022-11-17 05:28 UTC, clee231 requested changes

2022-11-17 05:28 UTC, clee231 commented on docs/kb/office-door.md
> +- Source code: https://github.com/SohamG/door-driver
Do you think we'll ever move this over to the lugatuic organization?

2022-11-17 05:28 UTC, clee231 commented on docs/kb/office-door.md
> +- This is the legacy card_reader.sh (now called `new_card_reader.sh` script modified to have `?` as the delimiter.
A PR for this new change should be made to the existing repo at https://github.com/lugatuic/doorkeeper-controller.

2022-11-17 05:28 UTC, clee231 commented on docs/kb/office-door.md
> +- If the card is of an allowed UIN, the python scirpt to open the door is called.
```suggestion
- If the card is of an allowed UIN, the python script to open the door is called.
```
Small typo.

2022-11-17 05:28 UTC, clee231 commented on docs/kb/office-door.md
> +- Systemd user service called `doorkeeper.service` located in `/home/pi/.config/systemd/user/doorkeeper.service`
TODO: We should commit this systemd service to the project repo.

2022-11-17 05:28 UTC, clee231 commented on docs/kb/office-door.md
> +- The output of the EVDEV Driver is piped to this shell script.
```suggestion
- The output of the EVDEV driver is piped to this shell script.
```
Capitalization nitpick.

2022-11-17 05:28 UTC, clee231 commented on docs/kb/office-door.md
> +- This shell script calls the EVDEV Driver with its output piped to `new_card_reader.sh`
```suggestion
- This shell script calls the EVDEV driver with its output piped to `new_card_reader.sh`
```
Capitalization nitpick.

2022-11-17 05:28 UTC, clee231 commented on docs/kb/office-door.md
> +- Systemd system service called discordbot.service.
```suggestion
- Systemd system service called `discordbot.service`.
```
Formatting nitpick.

2022-11-17 05:28 UTC, clee231 commented on docs/kb/office-door.md
> +1. MagStripe Reader for reading UIC ID Cards.
```suggestion
1. MagStripe reader for reading UIC ID cards.
```
Capitalization suggestion.

2022-11-17 05:28 UTC, clee231 commented on docs/kb/office-door.md
> +2. Discord bot to open the door from discord
```suggestion
2. Discord bot to open the door from Discord
```
Grammar Nitpick: Proper nouns should be capitalized.

2022-11-17 05:28 UTC, clee231 commented on docs/kb/office-door.md
> +- The card reader is basically the keyboard, presented in /dev/input/eventX.
```suggestion
- The card reader is basically the keyboard, presented in `/dev/input/eventX`.
```
Formatting suggestion.

2022-11-17 05:28 UTC, clee231 commented on docs/kb/office-door.md
> +- This is the legacy card_reader.sh (now called `new_card_reader.sh` script modified to have `?` as the delimiter.
```suggestion
- This is the legacy `card_reader.sh` (now called `new_card_reader.sh` script modified to have `?` as the delimiter.
```
Formatting suggestion.

2022-11-17 05:28 UTC, clee231 commented on docs/kb/office-door.md
> +- UIC ID Cards have ? as the last character.
```suggestion
- UIC ID cards have ? as the last character.
```
Capitalization suggestion.

2022-11-17 16:53 UTC, SohamG commented on docs/kb/office-door.md
> +- Source code: https://github.com/SohamG/door-driver
Uh yeah I accidentally created the repo in my personal account. I'll get it over to lugatuic

2022-11-17 17:30 UTC, SohamG commented on docs/kb/office-door.md
> +- This is the legacy card_reader.sh (now called `new_card_reader.sh` script modified to have `?` as the delimiter.
Sure. I think I should probably make that repo a submodule in the driver repo

2022-11-17 17:42 UTC, SohamG commented
UPDATE: Made new repo https://github.com/lugatuic/doorkeeper-driver as a meta repo (kinda). Tracking project specific stuff there. LMK if theres anything else other than the issues on that repo. 

PS I will be squashing once i have the :white_check_mark:

2022-11-19 03:18 UTC, bmiddha commented on docs/kb/office-door.md
> +   - Repo: https://github.com/lugatuic/doorkeeper-driver
```suggestion
   - Repository: [lugatuic/doorkeeper-driver](https://github.com/lugatuic/doorkeeper-driver)
```

nit: avoid bare links. and when using bare links wrap them in `<link>`

2022-11-30 06:00 UTC, clee231 requested changes
Sounds like PR checks are failing because you need to run `prettier`?

2023-01-06 13:27 UTC, closed without merging