✨ add agenda component
acm-uic/acm-uic.github.io pull request #56
Opened 2021-09-05 21:49 UTC by bmiddha

closes #30

2021-09-06 20:56 UTC, bmiddha commented
resolved merge conflicts

2021-09-06 22:09 UTC, clee231 requested changes

2021-09-06 22:09 UTC, clee231 commented on src/components/EventsAgenda/EventsAgenda.tsx
> +  }
![image](https://user-images.githubusercontent.com/1387910/132262829-808baeb7-5f90-427f-b2b1-9056ef9f42b8.png)
![image](https://user-images.githubusercontent.com/1387910/132262850-1e6117b1-9ab2-4da6-a203-0d319bc8ee00.png)

We might need to do some special logic for all-day events.
I also noticed for the events like the "US Department of Energy Hackathon" event, the website lists the date as September 17-18, but the Google calendar actually shows it as an all-day event on September 18th.

The API seems to actually returns the two dates:
> https://content.googleapis.com/calendar/v3/calendars/kc72g1ctfg8b88df34qqb62d1s@group.calendar.google.com/events?singleEvents=true&key=key_goes_here&timeMin=2021-09-06T21:56:12.810Z&timeMax=2022-09-06T21:56:12.810Z&maxResults=10
```
[...]
"items": [
  {
   "kind": "calendar#event",
   "etag": "\"3259031633234000\"",
   "id": "64cdse3g5mll65jqaqumllq8ld",
   "status": "confirmed",
   "htmlLink": "https://www.google.com/calendar/event?eid=NjRjZHNlM2c1bWxsNjVqcWFxdW1sbHE4bGQga2M3MmcxY3RmZzhiODhkZjM0cXFiNjJkMXNAZw",
   "created": "2021-08-21T03:16:56.000Z",
   "updated": "2021-08-21T03:16:56.617Z",
   "summary": "US Department of Energy Hackathon",
   "creator": {
    "email": "chase@acm.cs.uic.edu"
   },
   "organizer": {
    "email": "kc72g1ctfg8b88df34qqb62d1s@group.calendar.google.com",
    "displayName": "ACM@UIC",
    "self": true
   },
   "start": {
    "date": "2021-09-18"
   },
   "end": {
    "date": "2021-09-19"
   },
   "transparency": "transparent",
   "iCalUID": "64cdse3g5mll65jqaqumllq8ld@google.com",
   "sequence": 0,
   "eventType": "default"
  },
[...]
```
So, we may need to check the duration first to display this properly.

2021-09-07 02:22 UTC, bmiddha commented on src/util/getEvents.ts
> +    singleEvents: "true",
for got to sort events. fixed

2021-09-07 02:23 UTC, bmiddha commented on src/components/EventsAgenda/EventsAgenda.tsx
> +  }
Added a trivial check to see if it's an all day event. not sure how it will work with daylight savings.

2021-09-07 04:55 UTC, clee231 approved these changes
This is amazing! :star_struck: :+1: 
Thanks for all the hard work Bharat! 
I'll marvel at your code everyday! :nerd_face:

2021-09-07 04:55 UTC, merged