Add links to other orgs in footer
acm-uic/acm-uic.github.io pull request #88
Opened 2021-10-03 01:16 UTC by SohamG

Signed-off-by: Soham S Gumaste <sohamg2@gmail.com>

Let me know what other orgs need to be added.

Also we probably should break up the docusaurus config into smaller json/js files according to feature.

2021-10-03 01:56 UTC, clee231 requested changes

2021-10-03 01:56 UTC, clee231 commented on docusaurus.config.js
> +const lugLink = "https://acm.cs.uic.edu";
This is the wrong URL.

2021-10-03 01:56 UTC, clee231 commented on docusaurus.config.js
> +              label: "LUG@UIC",
Technically, all these organizations are `@UIC`. We can probably omit that and just name of the link `LUG`.

2021-10-03 05:49 UTC, bmiddha commented on docusaurus.config.js
> +              label: "LUG@UIC",
In that case the title could be updated to reflect that the links are related to UIC.

2021-10-03 05:49 UTC, bmiddha commented on docusaurus.config.js
> +const lugLink = "https://acm.cs.uic.edu";
good catch

2021-10-03 08:39 UTC, clee231 commented on docusaurus.config.js
> +              label: "LUG@UIC",
Do you think we would ever have a need to add other non-UIC orgs? I know on the old site, we did have a link back to something like acm.org... but maybe that would go elsewhere.

2021-10-03 18:13 UTC, bmiddha commented on docusaurus.config.js
> +              label: "LUG@UIC",
Maybe.
We can consider something like "External Links" or perhaps have different headings for UIC things and other things?

2021-10-03 19:09 UTC, SohamG commented on docusaurus.config.js
> +              label: "LUG@UIC",
Ive made these changes. Anything else before we can close this?

2021-10-03 19:15 UTC, bmiddha commented
Looks like you're including changes from another PR.
Please cleanup the branch with just your changes.
Other than that, looks good!

2021-10-03 19:22 UTC, SohamG commented
i hate git

2021-10-03 19:35 UTC, bmiddha approved these changes

2021-10-03 19:37 UTC, bmiddha requested changes

2021-10-03 19:37 UTC, bmiddha commented on docusaurus.config.js
> +              href: wicsLink,
use `logicaLink` here.

2021-10-03 19:43 UTC, bmiddha approved these changes

2021-10-04 00:18 UTC, clee231 approved these changes

2021-10-04 00:18 UTC, merged